export const enrollmentForms = [
  {
    fieldName: "firstName",
    defaultValue: "",
    formType: "text",
    label: "First Name",
    containerLength: "flex-1/4",
  },
  {
    fieldName: "lastName",
    defaultValue: "",
    formType: "text",
    label: "Last Name",
    containerLength: "flex-1/4",
  },
  {
    fieldName: "middleName",
    defaultValue: "",
    formType: "text",
    label: "Middle Name",
    containerLength: "flex-1/4",
  },
  {
    fieldName: "suffix",
    defaultValue: "",
    formType: "text",
    label: "Suffix",
    containerLength: "flex-1/8",
  },
  //   { fieldName: "email", defaultValue: "", formType: "text", label: "Email" },
  {
    fieldName: "cityAddress",
    defaultValue: "",
    formType: "text",
    label: "City Address",
    containerLength: "flex-3/4",
  },
  {
    fieldName: "contactNumber",
    defaultValue: "",
    formType: "text",
    label: "Contact Number",
    containerLength: "flex-1/5",
  },
  {
    fieldName: "provincialAddress",
    defaultValue: "",
    formType: "text",
    label: "Provincial Address",
    containerLength: "flex-3/4",
  },
  {
    fieldName: "sex",
    defaultValue: "",
    formType: "text",
    label: "Sex",
    containerLength: "flex-1/5",
  },
  {
    fieldName: "birthPlace",
    defaultValue: "",
    formType: "text",
    label: "Birth Place",
    containerLength: "flex-1/5",
  },
  {
    fieldName: "birthDate",
    defaultValue: "",
    formType: "text",
    label: "Birth Date",
    containerLength: "flex-1/5",
  },
  {
    fieldName: "religiousAffiliation",
    defaultValue: "",
    formType: "text",
    label: "Religious Affiliation",
    containerLength: "flex-1/5",
  },
  {
    fieldName: "civilStatus",
    defaultValue: "",
    formType: "text",
    label: "Civil Status",
    containerLength: "flex-1/5",
  },
];

export const parentForms = [
  {
    fieldName: "fatherName",
    defaultValue: "",
    formType: "text",
    label: "Father Name",
    containerLength: "flex-1/5",
  },
  {
    fieldName: "fatherOccupation",
    defaultValue: "",
    formType: "text",
    label: "Father Occupation",
    containerLength: "flex-1/5",
  },
  {
    fieldName: "fatherContactNumber",
    defaultValue: "",
    formType: "text",
    label: "Father Contact Number",
    containerLength: "flex-1/5",
  },
  {
    fieldName: "fatherAddress",
    defaultValue: "",
    formType: "text",
    label: "Father Address",
    containerLength: "flex-4/4",
  },
  {
    fieldName: "motherName",
    defaultValue: "",
    formType: "text",
    label: "Mother Name",
    containerLength: "flex-1/5",
  },
  {
    fieldName: "motherOccupation",
    defaultValue: "",
    formType: "text",
    label: "Mother Occupation",
    containerLength: "flex-1/5",
  },
  {
    fieldName: "motherContactNumber",
    defaultValue: "",
    formType: "text",
    label: "Mother Contact Number",
    containerLength: "flex-1/5",
  },
  {
    fieldName: "motherAddress",
    defaultValue: "",
    formType: "text",
    label: "Mother Address",
    containerLength: "flex-4/4",
  },
  {
    fieldName: "guardianName",
    defaultValue: "",
    formType: "text",
    label: "Guardian Name",
    containerLength: "flex-1/4",
  },
  {
    fieldName: "guardianRelationship",
    defaultValue: "",
    formType: "text",
    label: "Guardian Relationship",
    containerLength: "flex-1/4",
  },
  {
    fieldName: "guardianContactNumber",
    defaultValue: "",
    formType: "text",
    label: "Guardian Contact Number",
    containerLength: "flex-1/4",
  },
  //   {
  //     fieldName: "employerName",
  //     defaultValue: "",
  //     formType: "text",
  //     label: "Employer Name",
  //   },
  //   {
  //     fieldName: "occupation",
  //     defaultValue: "",
  //     formType: "text",
  //     label: "Occupation",
  //   },
  //   {
  //     fieldName: "employerAddress",
  //     defaultValue: "",
  //     formType: "text",
  //     label: "Employer Address",
  //   },
  //   {
  //     fieldName: "employerContactNumber",
  //     defaultValue: "",
  //     formType: "text",
  //     label: "Employer Contact Number",
  //   },
];

export const educationalBackgroundForms = [
  {
    fieldName: "elementarySchool",
    defaultValue: "",
    formType: "text",
    label: "Elementary School",
    containerLength: "flex-3/4",
  },
  {
    fieldName: "elementaryYearGraduated",
    defaultValue: "",
    formType: "text",
    label: "Elementary Year Graduated",
    containerLength: "flex-1/5",
  },
  {
    fieldName: "juniorHighSchool",
    defaultValue: "",
    formType: "text",
    label: "Junior High School",
    containerLength: "flex-3/4",
  },
  {
    fieldName: "juniorHighSchoolYearGraduated",
    defaultValue: "",
    formType: "text",
    label: "Junior High School Year Graduated",
    containerLength: "flex-1/5",
  },
  {
    fieldName: "seniorHighSchool",
    defaultValue: "",
    formType: "text",
    label: "Senior High School",
    containerLength: "flex-3/4",
  },
  {
    fieldName: "seniorHighSchoolYearGraduated",
    defaultValue: "",
    formType: "text",
    label: "Senior High School Year Graduated",
    containerLength: "flex-1/5",
  },
  {
    fieldName: "lastSchoolAttended",
    defaultValue: "",
    formType: "text",
    label: "Last School Attended",
    containerLength: "flex-3/4",
  },
  {
    fieldName: "lastSchoolAttendedYearGraduated",
    defaultValue: "",
    formType: "text",
    label: "Last School Attended Year Graduated",
    containerLength: "flex-1/5",
  },
];
